version: "3.1"

services:
  app:
    image: video-conferencing-app-webrtc
    build: .
    ports:
      - 3000:3000
    volumes:
      - ./components:/app/components
      - ./hooks:/app/hooks
      - ./lib:/app/lib
      - ./pages:/app/pages
      - ./public:/app/public
      - ./styles:/app/styles
      - ./types:/app/types
